### ISSUE TITLE
Longer input/output titles are truncated

### ISSUE THREAD

**Issue by milkmiruku** [OpenMusicKontrollers/patchmatrix#1]
Thanks for a wonderful program, makes a nice change from drawing and following virtual cables around :)

The problem I'm having is that some input (and output) titles get cut off - here's an example screenshot - http://i.imgur.com/TCJkBQm.png

**Comment by ventosus** [comment]
> makes a nice change from drawing and following virtual cables around
that is exactly the reason for having it written in the first place...

> The problem I'm having is that some input (and output) titles get cut off 
Yes, I know, I'm having the sample problem. It was a bad idea to concatenate 'client name' .. 'port name' in the first place.
And vertical text handling in the elementary toolkit is somewhat broken, too, I fear...
Will be fixed...

**Comment by ventosus** [comment]
matrix grid widget has been given a complete overhaul, now direclty paints to OpenGL-ES, much faster and scalable.

may still have some rough edges, but should fix truncated names (use the zoom in/out feature ) in b81ded7

**Comment by milkmiruku** [comment]
Looking good, nice one, thanks. I'll give it a proper try later, the main rough edge I see, and maybe this is a known, but the left hand colour bars and text are located past the left hand side of the window so I have to make the window larger than the desktop to see them ("PulseAudio Jack Sink" is long enough to see some of the text). fwiw, using 1280*1024.

**Comment by ventosus** [comment]
when zooming in alot, color bars and text will be pushed out of the patch area. There is still missing some logic to limit the zooming level to a reasonable range. that's one of the rough edges...

but you seem to have a different problem. it looks like the offset of the OpenGL surface is wrong. which version of EFL have you got?
e.g. 'pkg-config --modversion evas'

**Comment by milkmiruku** [comment]
1.17.0.

Ah, indeed, I realise now it appears there is extra space on the right side; I guess the colour bars should touch the sides but the grey lines extend beyond that (like [this](http://i.imgur.com/hciUPZt.png) n [that](http://i.imgur.com/Ya5CSsZ.png))

**Comment by ventosus** [comment]
Indeed, there was a bug for patchbay aspect ratios < 1.
Should be fixed in ae2c685.
