### ISSUE TITLE
windows binaries, where? and LS2 on windows

### ISSUE THREAD

**Issue by Leamucho** [OpenMusicKontrollers/patchmatrix#11]
Hello, I'm sorry if I'm just too naive, but does it mean I have to compile the binaries myself with the zip I download of the whole project?
If so, would you point me in the way of doing it? Qt? Visual Studio?
And also as LS2 is a linux stuff, what I'm supposed to do with the files I get from that project?

good day... thanks for taking time to read

**Comment by ventosus** [comment]
sorry, but this is not at all supported on windows, and won't ever.
