### ISSUE TITLE
unknow channel number

### ISSUE THREAD

**Issue by profejuanca** [OpenMusicKontrollers/patchmatrix#14]
Hi, I have a RME interface and mixer is confuse when try to connect channels because the order on channels is unpredictable, in a pair I see channel 1 together channel 10, the order is in the first digit, and channel 2 is before channel 20, 3 before 30 and 4 to 9 after 36.... its possible to correct this or add configuration options? In your first development the matrix are the best I think (similar to ardour).

**Comment by ventosus** [comment]
Thanks for reporting.

Patchmatrix should take that into account and should exactly do as you expect.

What version are you using?

    patchmatrix -v

**Comment by profejuanca** [comment]
Hi, I had to reinstall my system, sorry, I'am using manjaro now, the version is 0.20.0, but now don't start, the message is:

Copyright (c) 2016-2020 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
Using visual 0x24: R=8 G=8 B=8 A=8 D=24 DOUBLE=1 SAMPLES=0
X Error of failed request:  GLXBadDrawable
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Serial number of failed request:  45
  Current serial number in output stream:  52

I'm using nvidia propietary driver, you have an idea on this? thanks

**Comment by ventosus** [comment]
> I'm using nvidia propietary driver, you have an idea on this? thanks

Yes, that will be this issue here:

https://github.com/OpenMusicKontrollers/patchmatrix/issues/9

**Comment by profejuanca** [comment]
Thanks, I compiled and now works. Normally Manjaro is up-to-date, but this is not the case. Order rendering now is correct too, thanks again.
