### ISSUE TITLE
increase font size for hidpi displays

### ISSUE THREAD

**Issue by henning** [OpenMusicKontrollers/patchmatrix#15]
Is it possible - through command line options, environment variables, or maybe by setting some values at compile time or in source files, to get a bigger font that is more readable on hidpi disaplays with high resolutions?

**Comment by HorayNarea** [comment]
I'm not aware of options to set the font size on startup but as a workaround you can use Ctrl+Mousewheel to enlarge/shrink the UI

**Comment by ventosus** [comment]
@henning yes, it is.

Sadly there is no standard way of discovering hiDPI displays on Xorg (it actually lies about it, and always return 96DPI, to conform with other platforms (Windows, MacOS)).

GTK does its own thing, Qt also does its own thing.

Many other non{GTK, Qt} Applications kind of agree to read this out of the users's Xorg resource database.

    ~/.Xresources
    ------------------
    Xft.dpi: 200

P.s. don't forget to actually load that file into the database upon graphical session start.

    xrdb -load ~/.Xresources

@HorayNarea that feature has been disabled, iirc, because some users had issues with it.

**Comment by HorayNarea** [comment]
> @HorayNarea that feature has been disabled, iirc, because some users had issues with it.

So I can't zoom in/out anymore when my graph gets to complicated? That's …very very unfortunate.

**Comment by ventosus** [comment]
> So I can't zoom in/out anymore when my graph gets to complicated? That's …very very unfortunate.

Zooming has never been possible.

Dynamic zooming (which does not help in your case) has been possible, but has been deprecated.

One of these days/months/years there will be a new shiny UI that will suppot zooming.

**Comment by henning** [comment]
Thanks for the hints!

Unfortunately I am not successful.
I already had these settings in place, as I found out when looking at them with xrdb, which i was unfamiliar with until this day:

``
$ xrdb -q
*customization:	-color
Xft.dpi:	192
Xft.antialias:	1
Xft.hinting:	1
Xft.hintstyle:	hintslight
Xft.rgba:	rgb
Xcursor.size:	48
Xcursor.theme:	Yaru
``` 

and setting the dpi value significantly higher explicitly makes only the boxes in patchmatrix bigger, but the fonts stay nearly unreadable(with a normal distance from monitor) small.

At the same time, other X applications, especially qjackctl, get huge.

**Comment by ventosus** [comment]
@henning which version of patchmatrix is this?

    patchmatrix -v

Can you make 2 screenshots with Xft.dpi=96 and Xft.dpi=192?

**Comment by henning** [comment]
Finally...

```
$ ./build/patchmatrix -v
./build/patchmatrix 0.21.13
Copyright (c) 2016-2020 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
--------------------------------------------------------------------
This is free software: you can redistribute it and/or modify
it under the terms of the Artistic License 2.0 as published by
The Perl Foundation.

This source is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
Artistic License 2.0 for more details.

You should have received a copy of the Artistic License 2.0
along the source as a COPYING file. If not, obtain it from
http://www.perlfoundation.org/artistic_license_2_0.
```

**Comment by henning** [comment]
And here are the screenshots - i added an additional one where I set the dpi to 300... but the only difference is the size of the boxes and the squares of the working area....
From what I figured out looking at these things as closely as possible, I am not sure if patchmatrix is what I am looking for anyway. I am looking for a matrix like GUI for simple and easy patching my midi ports together, in the way as the midi ports are presented for example in ardour, but I do not want to use ardour. And i find qjackctl is working, but I dont like the chaotic way the patch screen looks and find it dificult to handle. 

Maybe your midi matrix plugin is what I really need, but I had no success to get it running in carla, and did not yet find anpother lv2 host that does it better. I will try "Jalv"  http://drobilla.net/software/jalv these days" - but more on that later in the midi matrix issue tracker when I have  questions about that. I just wanted to let you know that for me personally a fix is not needed anymore, unless you tell me patchmatrix is actually what I am looking for.

![Screenshot from 2020-12-30 20-07-27](https://user-images.githubusercontent.com/40272/103375633-f80f2480-4ada-11eb-98c8-47c3b5041a72.png)
![Screenshot from 2020-12-30 20-06-41](https://user-images.githubusercontent.com/40272/103375636-f8a7bb00-4ada-11eb-91fd-4b8b5cec7b66.png)
![Screenshot from 2020-12-30 20-05-36](https://user-images.githubusercontent.com/40272/103375639-f9405180-4ada-11eb-9563-443ef73ef5b0.png)

**Comment by ventosus** [comment]
> And here are the screenshots - i added an additional one where I set the dpi to 300... but the only difference is the size of the boxes and the squares of the working area....

Well, you have not installed patchmatrix. Thus the font (and icons) are not found and the toolkit falls back to a non-scalable embedded font face.

Just install itand it should work.

    cd build
    sudo ninja install

**Comment by ventosus** [comment]
> From what I figured out looking at these things as closely as possible, I am not sure if patchmatrix is what I am looking for anyway. I am looking for a matrix like GUI for simple and easy patching my midi ports together, in the way as the midi ports are presented for example in ardour, but I do not want to use ardour. And i find qjackctl is working, but I dont like the chaotic way the patch screen looks and find it dificult to handle.

patchmatrix is a somewhere in between a pure flow canvas patchbay (catia, patchage, new qjackctl) and a pure matrix patcher (ardour).

There is no standalone pure matrix patcher for JACK, afaik, so patchmatrix should be the closest thing you're looking for, indeed.

**Comment by henning** [comment]
oh sorry, my bad. 

I have that habit to usually never install simply do a "make install" on selfcompliled software without distribution packages before trying it out (because its difficult to remove it when i see that I dont need it) and this is somehow the first time ever I encounter this being a problem.

That being said, for the sake of being able to remove it cleanly when i see it does'nt fit my needs, can I install it to /opt/patchmatrix instead of spread in multiple directories in /usr/local, or will that fail, too?

Thanks for the explanation of the features!

**Comment by henning** [comment]
OK i looked into the ninja files and it seemed like there is an uninstall, so i gave it a try. 

Fonts is bigger, still a but small, but readable enough. 
That said, after a click in the canvas in the midi tab, it started to freeze, using 90% CPU, and I didn't get further. 

But that's not an hidpi issue. I will look into it another day when I have some more time and create another issue when I dont get it going! Thanks!

**Comment by ventosus** [comment]
> this is somehow the first time ever I encounter this being a problem.

Then you have not installed a lot of software :-), that's really rarely the case for non-trivial projects.

> can I install it to /opt/patchmatrix instead

Sure wherever you want.

> OK i looked into the ninja files and it seemed like there is an uninstall, so i gave it a try.

Yes, build tools without uninstall targets are a pain (cough, cough, yes I mean you CMake).
