### ISSUE TITLE
patchmatrix freezes and renders whole system nearly unusable after right click in midi tab

### ISSUE THREAD

**Issue by henning** [OpenMusicKontrollers/patchmatrix#16]
When trying out patchmatrix to be using it for midi connection / flow management, i dont get far.

Right after going to the midi tab, and doing a right click there, a box with some text appears, that I do not understand what it is for, and the application freezes, pulling the whole system into a state of nearly complete unresponsivess.

When looking into top it seems is uses huge amounts of memory, so probably theres something leaking:

```1022567 henning   20   0  113,7g  27,0g  80924 D  31,5  86,9   3:11.85 patchmatrix```

                                            
Version: commit id #707d248e01953a5d5955a6ff0dbdcd8ee92872fd                                        

![Screenshot from 2020-12-31 20-06-49_crop](https://user-images.githubusercontent.com/40272/103423161-6d472c00-4ba5-11eb-8f2c-3f70671f382d.png)

**Comment by henning** [comment]
I tried 0.20.0 too, to be sure it's not a HEAD development issue.
Same effect. 

In top (which I can use when switching quickly enough into it, I can watch how RAM is filled with something abouz a gigabyte per 10s... It might have something to do with the graphics system, as the system overall gets less reactive when I try to do anything with the application window like resizing or moving it.

OS is Ubuntu 20.10.

There where some warnings at build time, in case these are relevant:

```
[6/20] Compiling C object patchmatrix_mixer.p/patchmatrix_mixer.c.o
../patchmatrix_mixer.c: In function ‘_jack_session_cb’:
../patchmatrix_mixer.c:414:2: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  414 |  asprintf(&jev->command_line, "patchmatrix_mixer -u %s -d ${SESSION_DIR}",
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  415 |   jev->client_uuid);
      |   ~~~~~~~~~~~~~~~~~
In file included from ../patchmatrix_mixer.c:22:
../patchmatrix.h: In function ‘_mkdirp’:
../patchmatrix.h:467:2: warning: ignoring return value of ‘getcwd’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  467 |  getcwd(cwd, 1024);
      |  ^~~~~~~~~~~~~~~~~
../patchmatrix.h:469:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  469 |  chdir("/");
      |  ^~~~~~~~~~
../patchmatrix.h:477:3: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  477 |   chdir(sub);
      |   ^~~~~~~~~~
../patchmatrix.h:480:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  480 |  chdir(cwd);
      |  ^~~~~~~~~~
[10/20] Compiling C object patchmatrix.p/patchmatrix_jack.c.o
../patchmatrix_jack.c: In function ‘_jack_anim’:
../patchmatrix_jack.c:453:5: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  453 |     asprintf(&jev->command_line, "patchmatrix -u %s -d ${SESSION_DIR}",
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  454 |      jev->client_uuid);
      |      ~~~~~~~~~~~~~~~~~
In file included from ../patchmatrix_jack.h:21,
                 from ../patchmatrix_jack.c:18:
../patchmatrix.h: In function ‘_mkdirp’:
../patchmatrix.h:467:2: warning: ignoring return value of ‘getcwd’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  467 |  getcwd(cwd, 1024);
      |  ^~~~~~~~~~~~~~~~~
../patchmatrix.h:469:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  469 |  chdir("/");
      |  ^~~~~~~~~~
../patchmatrix.h:477:3: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  477 |   chdir(sub);
      |   ^~~~~~~~~~
../patchmatrix.h:480:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  480 |  chdir(cwd);
      |  ^~~~~~~~~~
[15/20] Compiling C object patchmatrix_monitor.p/patchmatrix_monitor.c.o
../patchmatrix_monitor.c: In function ‘_jack_session_cb’:
../patchmatrix_monitor.c:183:2: warning: ignoring return value of ‘asprintf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  183 |  asprintf(&jev->command_line, "patchmatrix_monitor -u %s -d ${SESSION_DIR}",
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  184 |   jev->client_uuid);
      |   ~~~~~~~~~~~~~~~~~
In file included from ../patchmatrix_monitor.c:22:
../patchmatrix.h: In function ‘_mkdirp’:
../patchmatrix.h:467:2: warning: ignoring return value of ‘getcwd’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  467 |  getcwd(cwd, 1024);
      |  ^~~~~~~~~~~~~~~~~
../patchmatrix.h:469:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  469 |  chdir("/");
      |  ^~~~~~~~~~
../patchmatrix.h:477:3: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  477 |   chdir(sub);
      |   ^~~~~~~~~~
../patchmatrix.h:480:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  480 |  chdir(cwd);
      |  ^~~~~~~~~~
[18/20] Linking target patchmatrix_monitor

[19/20] Compiling C object patchmatrix.p/patchmatrix.c.o
In file included from ../patchmatrix.c:20:
../patchmatrix.h: In function ‘_mkdirp’:
../patchmatrix.h:467:2: warning: ignoring return value of ‘getcwd’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  467 |  getcwd(cwd, 1024);
      |  ^~~~~~~~~~~~~~~~~
../patchmatrix.h:469:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  469 |  chdir("/");
      |  ^~~~~~~~~~
../patchmatrix.h:477:3: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  477 |   chdir(sub);
      |   ^~~~~~~~~~
../patchmatrix.h:480:2: warning: ignoring return value of ‘chdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  480 |  chdir(cwd);
      |  ^~~~~~~~~~
In file included from ../patchmatrix.h:45,
                 from ../patchmatrix.c:20:
../varchunk/varchunk.h: In function ‘varchunk_new’:
../varchunk/varchunk.h:145:2: warning: ignoring return value of ‘posix_memalign’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  145 |  posix_memalign((void **)&varchunk, sizeof(varchunk_elmnt_t), total_size);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by ventosus** [comment]
thanks for reporting, sadly, I cannot reproduce this.

> Right after going to the midi tab, and doing a right click there, a box with some text appears, that I do not understand what it is for, and the application freezes, pulling the whole system into a state of nearly complete unresponsivess.

To activate Audio/MIDI/OSC/CV tabs, just left click.

Right click on the canvas opens a context menu with which you can spawn embedded mixer and monitor clients.

**Comment by henning** [comment]
ok, seems like basically things work beside that. I can create midi connections in a matrix, as I wanted to. They are reloaded at program start... It would be a bit more easy to use if the Matrix would be labelled, so I can find the point in the matrix where i want to set a connection without hovering over all the fields (as in the lv2 plugin you made...).
It took my a bit to realize I need can read the manual to learn how to move the elements on the canvas - first thought it wasn't possible - in most apps I use moving elements on the screen/canvas is made by "grabbing" them with a right click and moving while holding the click - that would be what feels intuitive for me, but others may have other experiences and needs...

Looks like a very powerful tool! Some things i also wished for:
Would be great if it had an "undo", especially as removing a whole matrix with many connections can be removed with a single (wrong right-) click and there is not confirm question. 
Would also be great if there was save/load to store different configurations for different use cases.

I am not sure if I need more than the basic matrix/save/restore connections for now. I am just beginning to dive into working with midi systhesizers that need complex virtual cabling. I already wrote a little python script that does that for now, and think about adding a GUI Matrix to it. the python jack library is very easy to use...
But I will definitely get to a point where I need more advanced features! Hope we can identify/solve the memory issue until then...

**Comment by unsaph3** [comment]
I just had this identical issue and had to force restart my machine. This occurred while trying to report that the general GUI sometimes doesn't update changes correctly likeadding mixer/monitor sinks - no midi stuff here. Let me know where to look for log files, ect. I had taken an initial screen shot, then the whole program didn't render and when I went to move it on the desktop, boom system freeze. 

OS is Manjaro on a box with an i7 and 32gb of RAM.

**Comment by ventosus** [comment]
thanks for reporting, I've still not managed to reproduce this.

since 689a069cc76c818aadccb199a765ad9c952afe82, right click action to open the contextual menu is limited to the canvas region, which hopefully fixed this strange issue.
