### ISSUE TITLE
Ideas about general UX improvements

### ISSUE THREAD

**Issue by grammoboy2** [OpenMusicKontrollers/patchmatrix#17]
Interested to test it out, but it's a LV2 plugin?

Would be nice to use this functionality, without having to load a LV2 plugin host first.

Feature request: standalone version.

**Comment by ventosus** [comment]
> Interested to test it out, but it's a LV2 plugin?

???? where have you read that ? It's a JACKpatchbay.

**Comment by grammoboy2** [comment]
hm, looking at the build instructions it needs LV2 ...

Dependencies
Runtime

    JACK (JACK audio connection kit)

Buildtime

    LV2 (LV2 Plugin Specification)

**Comment by grammoboy2** [comment]
Interesting concept. Better organized then patchage probably and more fixed, you don't have to search a lot of your ports.

Disadvantage is that you've to 'hover' above the display of connection ports to be able to see what you're doing. In Patchage this is clear right away. This is especially the case in the midi tab I think. Maybe patchmatrix can display the midi output ports of non-sequencer in this case too.


Also connecting to a2j is less clear right away I think.


![Screenshot_2021-01-16_15-33-22](https://user-images.githubusercontent.com/378249/104814651-6f012880-5810-11eb-8387-863930ab9a0f.png)

![Screenshot_2021-01-16_15-34-03](https://user-images.githubusercontent.com/378249/104814654-7294af80-5810-11eb-8109-4995ab4cd2c0.png)

**Comment by grammoboy2** [comment]
Hm I like the fact that the clients have a fixed place indeed, which is a improvement compared to Patchage. 

I doubt whether the matrix helps here actually. Now you need to drag the cables AND select the right place in the matrix. 
At the end, Patchage is still faster now probably, also because the overview in patchmatrix is quite complex for the eyes/brain. 

Hmm but the fixed clients is interesting for sure...

**Comment by ventosus** [comment]
@grammoboy2 thanks, all valid inputs indeed. There's a new UI in the planning, which should tackle some of your issues.

Client position is stored as JACKmetadata, so is preserved as long as JACK is running.

LV2 is just headers and required at build time, indeed.

**Comment by grammoboy2** [comment]
Then I meant 'stored' ;) I saw it isn't fixed indeed.

Lately I was thinking that it was actually ridiculous how we linuxaudio users still have to search around in the patchbays for the right ports... :) Costs quite some time and waste of cognitive space... 

That made me think about possible ways to improve this and then also the Ardour connection matrix comes to mind, because all port are in place, no need to search. But I can imagine this also gets complex with many ports.

------

There are also some closed source patchbays

loopback
https://youtu.be/2njVkJ6Q6A4?t=1175

This seems to be fixed in place at least. No searching for the ports.
One can add sources, so not all the sources/ ports are available by default, less ports, less mess.

https://youtu.be/eDIE3vYpOJY?t=246

This certainly has some drawbacks compared to Patchage though. 

-----
About patchmatrix:

- Maybe the GUI can become more clear to the eye/brain when colors are used to emphasize distinctions between ports.
- More distinction in color between active and inactive clients (clients that are 'active' in other tabs) in a tab 
- Grey in general is hard for the eye/brain to distinguish differences probably. 
- Display the connection matrix vertically. Non-sequencer has many midi ports for instance, they've a numbering, more easy vertically. At least when you're used to patchage, this is more familiar. Probably also easier to arrange this in the canvas without cluttering, because the client names are displayed horizontally already. 
- Display both the ports of a client with stereo (or more) outputs on the canvas. A matrix box with just 4 choices (2 outputs, 2 inputs), appears already unnecessarily complex to me... (this would mean, remove the matrix boxes totally probably).

----

I would be interested to see how this patchmatrix works, if it would work the same as patchage, but with the fixed/ stored clients/ports positions.

**Comment by ventosus** [comment]
That's a prototype I've had at some time.

For stereo pairs, I want to be able to connect left to right and vice versa, so all options are needed.

![2021-01-16-173201_1920x1080_scrot](https://user-images.githubusercontent.com/1863184/104817349-01112d00-5821-11eb-9e69-cf78ac2ff20c.png)

**Comment by ventosus** [comment]
The problem with Ardours patch matrix is, that there I cannot see the signal flow at all. So patchmatrix tries to take the best of both worlds (patchage, Ardour).

**Comment by ventosus** [comment]
Also, patchmatrix offers automatic connections, e.g. for stereo pairs, when connecting, look at the README.

**Comment by grammoboy2** [comment]
Visually the prototype appears complex to me (eyes/brain), not really structured and all kind of angles. 
For me I don't care how it looks, it should be simple stupid and therefor fast to work with probably. But simple is difficult ...

Will look at the readme and do some testing. Most of the time NSM is doing the automatic (re-)connection for me.

**Comment by grammoboy2** [comment]
You're right about the ardour matrix and signal flow, good point.

**Comment by grammoboy2** [comment]
Quick mockup, stored positions (patchmatrix) with connecting ports (the patchage way)

![mockup0 01](https://user-images.githubusercontent.com/378249/104818111-d2e21c00-5825-11eb-976a-ceab3cff71b4.png)

A futuristic idea is connecting by speech probably.

"Matrix" "Connect" "A1" "B1"

Not sure if that will be faster though :)

**Comment by grammoboy2** [comment]
I see how you can use 'ctr' to connect both ports and all though I've only a few minutes of experience with it, I think I like it. But I can imagine the same can be accomplished without the matrix boxes. I still think those boxes make the view and use unnecessarily complex.

A disadvantage of patchmatrix compared to patchage, is that the ALSA midi clients in a2j are not visually displayed. I don't want to connect to a2j, I want to connect to the synth I just started, AlsaModularSynth (via a2j). 

Non-sequencer has 16 midi output port (jack midi). These are all displayed with every client you connect to. So connecting to synth1 gives me a matrix with 16 fields, connecting to synth2 gives me another matrix with 16 fields etc. Where-as in Patchage, the 16 ports of non-sequencer are displayed once. 

The matrix has a advantage if I want to connect non-sequencer to one midi synth with one input port. Then I can select every midi port I want fast and easy. All though it would be better to display the matrix vertically then I think.

**Comment by ventosus** [comment]
> I see how you can use 'ctr' to connect both ports and all though I've only a few minutes of experience with it, I think I like it. But I can imagine the same can be accomplished without the matrix boxes. I still think those boxes make the view and use unnecessarily complex.

Well, there could be an option *hide/show details*, where you would have to hower over a client connection to have the connection matrix details show up.

color coding is not a good idea at all because there's vast amounts of people that are color blind. That would be another project altogether, a kind of color-patchbay.

> A disadvantage of patchmatrix compared to patchage, is that the ALSA midi clients in a2j are not visually displayed. I don't want to connect to a2j, I want to connect to the synth I just started, AlsaModularSynth (via a2j).

Why are you still using a2j, it has been integrated into JACK1 since ages (jackd -X alsa_midi). Being an ALSA patchbay is out-of-scope for this project, it's a JACK patchbay.

> Non-sequencer has 16 midi output port (jack midi). These are all displayed with every client you connect to. So connecting to synth1 gives me a matrix with 16 fields, connecting to synth2 gives me another matrix with 16 fields etc. Where-as in Patchage, the 16 ports of non-sequencer are displayed once.

Sure, there's no ideal patchbay, that can efficiently handle all usage scenarios.

> The matrix has a advantage if I want to connect non-sequencer to one midi synth with one input port. Then I can select every midi port I want fast and easy. All though it would be better to display the matrix vertically then I think.

Yes, that's exactly the goal of this project.

**Comment by grammoboy2** [comment]
> > I see how you can use 'ctr' to connect both ports and all though I've only a few minutes of experience with it, I think I like it. But I can imagine the same can be accomplished without the matrix boxes. I still think those boxes make the view and use unnecessarily complex.
> 
> Well, there could be an option _hide/show details_, where you would have to hower over a client connection to have the connection matrix details show up.

> color coding is not a good idea at all because there's vast amounts of people that are color blind. That would be another project altogether, a kind of color-patchbay.

8% I think, where the problems are minor it seems. 
> 

> Why are you still using a2j, it has been integrated into JACK1 since ages (jackd -X alsa_midi). Being an ALSA patchbay is out-of-scope for this project, it's a JACK patchbay.

Most people are using jack2 I think. Not showing the alsa midi clients of a2j is a consequence of the fact that patchmatrix only displays a client as one instance, it doesn't display the available ports by default. 
> 

> > The matrix has a advantage if I want to connect non-sequencer to one midi synth with one input port. Then I can select every midi port I want fast and easy. All though it would be better to display the matrix vertically then I think.
> 
> Yes, that's exactly the goal of this project.

Isn't the goal to make a handy improved patchbay? Or is the goal to use matrices anyway, cause they're cool? ;) What do we miss if you would leave out the matrices, like in my mock-up? For me personally, the disadvantages out-weight the advantages of the matrices at the moment I think. 

But I'll try to use patchmatrix for a while to find out my experiences on longer term. I do like the stored positions for sure. 

Thanks for your work.

**Comment by grammoboy2** [comment]
Here is another idea, where a user just selects the right area in the 'matrix'. Then a visual connection is made with the usual vstual 'cable'. So instead of 'dragging' the cable, you select the spots in the 'matrix'
Here you've a matrix and all ports are available and doesn't need to be duplicated when you connect to a second softsynth.

![canvas_as_matrix0 01](https://user-images.githubusercontent.com/378249/104847966-1babda80-58e3-11eb-8d84-a3f546979c8d.png)

![canvas_as_matrix0 02](https://user-images.githubusercontent.com/378249/104848413-27000580-58e5-11eb-9d4e-696b12a05c32.png)

![canvas_as_matrix0 03](https://user-images.githubusercontent.com/378249/104848417-2b2c2300-58e5-11eb-9593-5b6bdc9de528.png)

**Comment by ventosus** [comment]
@grammoboy2 I'm sorry, but I don't get at all what you're trying to do.

from the README:

> A simple graphical JACK patchbay that tries to unite the best of both worlds:
>
> * Fast patching and uncluttered port representation of a **matrix patchbay**
> * Excellent representation of signal flow of a **flow canvas patchbay**

That's pretty much it, and it won't change. Some minor UX improvement here and there is possible, but that's all.

**Comment by grammoboy2** [comment]
Sharing ideas about general UX improvements.

**Comment by grammoboy2** [comment]
You reply surprises me though, because you seems to be open for suggestions and re-open a issue for it. 
Some disadvantages are reported, then a prototype which solves those issues maybe is added, which has still the advantages of your design. Then you don't get it anymore and close the door. Hmm

**Comment by ventosus** [comment]
> Some disadvantages are reported, then a prototype which solves those issues maybe is added, which has still the advantages of your design. Then you don't get it anymore and close the door. Hmm

Where do I close the door? This issue is stil open, isn't it?

I'm just being clear and honest what this project is about. Patchmatrix does exactly what it should do, it won't change radically, because then it wouldn't be useful for me anymore. There's room for improvement here and there, and it has been discussed in this issue, which is very much appreciated, but that's it, really.

>> I'm sorry, but I don't get at all what you're trying to do.

This obviously is referring to your screenshots, they make no sense to me and I just don't get what you're trying to do there, I cannot see which ports are connected together. The latter is the least a patchbay should be able to represent.

**Comment by grammoboy2** [comment]
No problem, I've removed the 2nd screenshot, which was especially confusing maybe.

Main point is that I like the stored positions and the tabs for audio/midi/cv/osc, but doubt whether this approach of matrices really gives you a faster patching workflow and less cluttered workspace compared to solutions like Patchage.

Anyway, good luck.

**Comment by profejuanca** [comment]
Hi, you know the (video) composing tools? these have many modes, one called "nodes" for see the signal flow. The RME Totalmix for RME cards have a double visualization mode, one called matrix and other called mixer, M key show mixer and X key the matrix mode, both are useful depending on the context of use. Video Composing software (like Natron or Nuke, Natron is FOSS) have a "box" or container for grouping a entire "circuit" and a click open a new window with a sub-canvas on it (window is a simplification), but this can be merged with a list or some different idea for seeing the group, maybe for see the content of a lv2 or vst host?

I think your original idea for a 45 degrees matrix style is very interesting or the ardour approach too, and a "nodes" style like your current style are not opposites and can coexist in the program in a "modes" approach.

**Comment by MarioMey** [comment]
Oh, I see that this thread has 6 years and the last comment is from jan 2020. I think it is not under development any more, is it?
