### ISSUE TITLE
[feature request] UI enhancements for large numbers of ports

### ISSUE THREAD

**Issue by jrigg** [OpenMusicKontrollers/patchmatrix#18]
This is a nice program with a good concept. I like the clean appearance and the fact that it avoids GTK and Qt.

There are a couple of things that would improve usability when using large numbers of audio ports and JACK clients however:

1 - Add a fixed display of the matrix crosspoint text, eg. in a toolbar. I use RME MADI cards, and the matrices for the system audio ports are too tall to fit on the screen.  When making connections near the top, the text that appears below the matrix on mouse hover isn't visible. An additional fixed position display of that text would solve the problem.

2 - Toggle visibility of matrices on a per-client basis, to reduce clutter when using a lot of JACK clients.

**Comment by ventosus** [comment]
thanks, good ideas, indeed, (2) was already on the TODO list.

**Comment by jrigg** [comment]
> (2) was already on the TODO list.

Ah, great.  I currently use Patchage, which is fine but it relies on GTK2. Apart from a personal preference for lightweight software, having to compile an obsolete version of GTK or Qt from scratch to support one or two indispensable programs in future is a pain I prefer to avoid.

The one thing that has prevented me from removing all GTK and Qt from my DAWs so far has been the lack of a suitable JACK connection manager. Patchmatrix looks very promising here.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/8>
