### ISSUE TITLE
doesn't work on ubuntu 16.04

### ISSUE THREAD

**Issue by rhetr** [OpenMusicKontrollers/patchmatrix#2]
i successfully compiled patchmatrix and also had to install `evas` for it to work but now I'm getting the following errors:

```
Jack: JackClient::kGraphOrderCallback
ERR<5884>:evas_main lib/evas/canvas/evas_gl.c:42 evas_gl_new() Evas GL engine not available.
ERR<5884>:elementary elm_glview.c:220 _elm_glview_smart_add() Failed Creating an Evas GL Object.

ERR<5884>:eo lib/eo/eo.c:1217 eo_error_set_internal() Error with obj '0x10da4f0' at elm_glview.c:301
ERR<5884>:eo lib/eo/eo.c:1107 eo_add_internal() in elm_glview.c:285, Object of class 'Elm_Glview' - One of the object constructors have failed.
ERR<5884>:eo lib/eo/eo_ptr_indirection.x:275 _eo_obj_pointer_get() obj_id (nil) is not pointing to a valid object. Maybe it has already been freed.
```

which is probably related to me not being able to see the actual matrix in the patchmatrix window. Anyway I installed all the libevas libraries in the ubuntu repository so I don't know what else i need to do to get this working. maybe the packaged efl libs are out of date or i need something else?

**Comment by ventosus** [comment]
Thanks for testing patchmatrix

What Ubuntu version are you running at?

The matrix is rendered via OpenGL-ES (either via hardware or via software). You thus need the evas GL engine installed for the matrix to be rendered.

According to your error, the evas X11 GL engine is not installed on your system.

Evas engines are usually installed in '/usr/lib/evas/modules/engines'

You should have 'gl_generic' and 'gl_x11' folders in there.

IIRC, the corresponding package in Debian/Ubuntu is 'libevas1-engines-x'
http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libevas1-engines-x&searchon=names

**Comment by rhetr** [comment]
i'm running 16.04.1. I do have libevas1-engines-x installed, i did a `dpkg-query -L libevas1-engines-x` to find the location of the installed files:
```
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/evas
/usr/lib/x86_64-linux-gnu/evas/modules
/usr/lib/x86_64-linux-gnu/evas/modules/engines
/usr/lib/x86_64-linux-gnu/evas/modules/engines/software_x11
/usr/lib/x86_64-linux-gnu/evas/modules/engines/software_x11/linux-gnu-x86_64-1.8.6
/usr/lib/x86_64-linux-gnu/evas/modules/engines/software_x11/linux-gnu-x86_64-1.8.6/module.so
/usr/lib/x86_64-linux-gnu/evas/modules/engines/gl_x11
/usr/lib/x86_64-linux-gnu/evas/modules/engines/gl_x11/linux-gnu-x86_64-1.8.6
/usr/lib/x86_64-linux-gnu/evas/modules/engines/gl_x11/linux-gnu-x86_64-1.8.6/module.so
/usr/share
/usr/share/doc
/usr/share/doc/libevas1-engines-x
/usr/share/doc/libevas1-engines-x/copyright
/usr/share/doc/libevas1-engines-x/changelog.Debian.gz
```
then I ran `tree /usr/lib/x86_64-linux-gnu/evas/`:
```
/usr/lib/x86_64-linux-gnu/evas/
├── modules
│   ├── engines
│   │   ├── fb
│   │   │   └── linux-gnu-x86_64-1.8.6
│   │   │       └── module.so
│   │   ├── gl_x11
│   │   │   └── linux-gnu-x86_64-1.8.6
│   │   │       └── module.so
│   │   └── software_x11
│   │       └── linux-gnu-x86_64-1.8.6
│   │           └── module.so
│   ├── loaders
│   │   ├── gif
│   │   │   └── linux-gnu-x86_64-1.8.6
│   │   │       └── module.so
│   │   └── tiff
│   │       └── linux-gnu-x86_64-1.8.6
│   │           └── module.so
│   └── savers
│       └── tiff
│           └── linux-gnu-x86_64-1.8.6
│               └── module.so
└── utils
    ├── evas_image_loader.arw -> evas_image_loader.raw
    ├── evas_image_loader.cr2 -> evas_image_loader.raw
    ├── evas_image_loader.crw -> evas_image_loader.raw
    ├── evas_image_loader.dcr -> evas_image_loader.raw
    ├── evas_image_loader.dng -> evas_image_loader.raw
    ├── evas_image_loader.erf -> evas_image_loader.raw
    ├── evas_image_loader.k25 -> evas_image_loader.raw
    ├── evas_image_loader.kdc -> evas_image_loader.raw
    ├── evas_image_loader.mrw -> evas_image_loader.raw
    ├── evas_image_loader.nef -> evas_image_loader.raw
    ├── evas_image_loader.nrf -> evas_image_loader.raw
    ├── evas_image_loader.nrw -> evas_image_loader.raw
    ├── evas_image_loader.orf -> evas_image_loader.raw
    ├── evas_image_loader.pef -> evas_image_loader.raw
    ├── evas_image_loader.ps
    ├── evas_image_loader.raf -> evas_image_loader.raw
    ├── evas_image_loader.raw
    ├── evas_image_loader.rw2 -> evas_image_loader.raw
    ├── evas_image_loader.sr2 -> evas_image_loader.raw
    ├── evas_image_loader.srf -> evas_image_loader.raw
    ├── evas_image_loader.svg
    ├── evas_image_loader.svg.gz -> evas_image_loader.svg
    ├── evas_image_loader.svgz -> evas_image_loader.svg
    ├── evas_image_loader.x3f -> evas_image_loader.raw
    ├── evas_image_loader.xcf
    └── evas_image_loader.xcf.gz -> evas_image_loader.xcf

17 directories, 32 files
```

So it looks like it's there but just not being used? I also tried `sudo apt-get install libevas1-engines-x:i386` since I thought it might install directly into `/usr/lib/` (i'm just guessing) but doesn't work:
```
The following packages have unmet dependencies:
 libevas1-engines-x:i386 : Depends: libevas1:i386 (>= 1.8.0) but it is not going to be installed
```
```
sudo apt-get install libevas1:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libevas1:i386 : Depends: libevas-loaders:i386 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
```
sudo apt-get install libevas1-loaders:i386
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libevas1-loaders:i386
```

The last thing i tried was `ln -s /usr/lib/x86_64-linux-gnu/evas /usr/lib/evas` but that didn't solve anything either.

**Comment by ventosus** [comment]
hmm, your installation seems to be fine, indeed.

It seems that you have the OpenGL evas engine installed, but it cannot be used...

Can you check that OpenGL in evas is working at all on your system in another app, e.g. with 'elementary_test'? if it is at all available on Ubuntu, it is here on ArchLinux.

EFL libraries on Ubuntu seem to be *really* outdated. Maybe you want to try with an up-to-date PPA
https://www.enlightenment.org/distros/ubuntu-start

**Comment by rhetr** [comment]
I don't use enlightenment stuff often so I don't really know... I tried `apt-cache search elementary_test` but didn't come up with anything. Unfortunately that ppa doesn't have anything working for 16.04 (xenial) as it says on that page, i tried installing it anyway but then libevas wasn't even there so i had to revert.

**Comment by ventosus** [comment]
so, I've spun up an ubuntu 16.04 image and can confirm the issue.

the EFL libraries are way too outdated on Debian/Ubuntu, so I've enabled the enlightenment-git PPA to look whether up-to-date libraries do help:
https://launchpad.net/~enlightenment-git/+archive/ubuntu/ppa

but even that does not help. there does not seem to be anything wrong with my code, as the 'elementary_test' app has non-functional OpenGL rendering, too.

EFL + OpenGL just seems to be broken on Ubuntu, not much I can do...

**Comment by rhetr** [comment]
hm, that's too bad. I'm not to keen on building efl from source but I will update this issue if I make any progress otherwise

**Comment by ventosus** [comment]
engine has been migrated to plain OpenGL, closing this
