### ISSUE TITLE
Flatpak Packaging

### ISSUE THREAD

**Issue by drewofdoom** [OpenMusicKontrollers/patchmatrix#21]
Considering that Patchmatrix works so well with Pipewire, it would be great to package it up with Flatpak and publish it to Flathub. More and more pro-audio applications are landing on Flathub, and Patchmatrix would be a perfect complement.

I am totally new to Flatpak packaging, but I would be more than happy to help.

**Comment by ventosus** [comment]
thanks, but no, I consider flatpak and its consorts pure atrocities.
