### ISSUE TITLE
Tab icons render as white squares

### ISSUE THREAD

**Issue by Natronium** [OpenMusicKontrollers/patchmatrix#22]
Running patchmatrix-v0.24.0 (though the issue is also present with a hand-built version from the latest git commit 79cac7) on amd64 Debian Testing (using X and Pipewire) the icons for the Audio, Midi, CV and OSC tabs all render as white squares:
![2021-05-14-102119_605x57_scrot](https://user-images.githubusercontent.com/25114018/118284208-2d227f00-b49e-11eb-9b56-2003bd39dc3b.png)

everything else seems to work fine (aside from the segfault i mentioned in #23 ) and the only console output is complaints from pipewire-jack. i wasn't sure how related this was to the segfault issue in #23 so i figured it deserved its own issue.

**Comment by ventosus** [comment]
You likely have not installed the (hand-built) application and the resources are not found.

**Comment by Natronium** [comment]
that sounds very likely, though it's worth noting that this is true of the prebuilt binaries as well (run from their own directory where i unpacked them somewhere in /tmp). looking at output from `strace` it seems like the only place it actually looks for the icons is `/builds/OpenMusicKontrollers/patchmatrix/patchmatrix-0.24.0/x86_64-linux-gnu-bullseye/share/patchmatrix/audio.png` which seems a little impractical as installation locations go.

**Comment by ventosus** [comment]
thanks for reporting

fixed in bd35f4ba724a3483dda0677edcf7dc9e6c7759a9
