### ISSUE TITLE
Context menu options cut off at bottom of menu

### ISSUE THREAD

**Issue by unsaph3** [OpenMusicKontrollers/patchmatrix#24]
Context menu options are cut off on the bottom of the menu, as you can see by my screenshot.
![Context_menu_cutoff](https://user-images.githubusercontent.com/72213598/120586250-0b0a8580-c3e8-11eb-9dc0-b352d990b531.jpg)

**Comment by ventosus** [comment]
thanks for reporting, fixed in a4f09491b570da01afa2de4cf827b719c89c3af6
