### ISSUE TITLE
[Feature request] UI enhancements for Pipewire

### ISSUE THREAD

**Issue by jeffbeale** [OpenMusicKontrollers/patchmatrix#25]
As pipewire becomes more mature, it would be nice to see this particular patchbay tool adapt to the times
Some ideas include
- Tooltips that include a button to create a 'rule' that saves in the jack.conf file located in ./config/pipewire. Rules are structured as
```
{
        matches = [
            {client.name = "Carla"}
        ]
        actions = {
            update-props = {
                node.latency = 128/48000
            }
        }
    }
```
- Tooltips that include the current buffer size per application (buffer size application is calling the server for) - this enables you to scan through quickly to see which application is forcing the buffer size lower/greater than the expected buffer size for the application
- Coloring nodes based on whether they are calling the Pulse backend or the JACK backend
- Native Pipewire awareness (rather than using pipewire-jack)

If this is outside the scope of this project, I understand.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/7>
