### ISSUE TITLE
Stable release file is a 404 page.

### ISSUE THREAD

**Issue by MarioMey** [OpenMusicKontrollers/patchmatrix#27]
Here: https://github.com/OpenMusicKontrollers/patchmatrix#stable-release
And this is the file that doesn't exist: https://dl.open-music-kontrollers.ch/patchmatrix/stable/patchmatrix-0.26.0.zip

Also, I check that folder and there are builts up to 0.18.0:

![imagen](https://user-images.githubusercontent.com/4954109/137667561-80bfd09b-cef2-4037-9aba-8f132d2bfef9.png)

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/6>
