### ISSUE TITLE
Cannot Move Stacked UI Items Individually

### ISSUE THREAD

**Issue by Swivelgames** [OpenMusicKontrollers/patchmatrix#28]
If a UI item is inadvertently placed on top of another (or spawns there), there is no way to unstack them. Attempting to move the UI item that is on the top of the other will move both, and they will be stacked permanently from then on.

**Comment by ventosus** [comment]
thanks for reporting, can reproduce this issue.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/5#event-16>
