### ISSUE TITLE
[bug] Mixers and monitors not always spawning correctly.

### ISSUE THREAD

**Issue by JustCryen** [OpenMusicKontrollers/patchmatrix#29]
First of all, I want to mention that I use pipewire with pipewire-jack.
This issue might be directly related to this fact so I just wanted to be up front with it.

### The issue
When I first tried creating mixers and monitors it all worked fine but for some time now I'm unable to get a working one.
It all spawns a sink with inputs and outputs but not a visual representation of the tool I wanted to get.
![image](https://user-images.githubusercontent.com/41633661/150800521-c6e9c5f9-b077-4fa1-9925-5e6218ff541b.png)

I have some other issues but I'll probably create a separate thread for those since it would be more of an improvement suggestion than a bug.

**Comment by JustCryen** [comment]
Oh yeah, and I can't remove them.
I can move them and connect to other devices / programs but they don't do anything.
Some of them don't pass audio (miksers) and some do… so I don't know what's up with that.

**Comment by mneiger** [comment]
same here

**Comment by JustCryen** [comment]
I figured out that using `killall patchmatrix_mixer` and `killall patchmatrix_monitor` commands does in fact remove the broken nodes and after that I'm able to create a working one again.

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/4>
