### ISSUE TITLE
Display Takeover/shutdown

### ISSUE THREAD

**Issue by VegaDeftwing** [OpenMusicKontrollers/patchmatrix#3]
* Program Launches
* Interface is visable but incorrectly scaled
* Interface rescales to match window size
* All is OK
* click on any object on screen -> **laptop display goes black**
* program, if on external display, stays active and 'useable'
* program appears to respond sluggishly and even when holding CTRL to move an object the object may lose focus and be 'dropped'
* some visual artifacts result from sluggishness; lines and dots not rendered in real time and lag behind

upon checking using xrandr the display still appears to be connected and responding. Im not exactly sure if I am still able to drag a mouse over or not.
The only fix after it occurs seems to be restarting the entire system.

This is honestly one of the strangest bugs I have ever encountered on linux
Running the latest version from the AUR 0.8.0-1
Hardware is an [MSI GE72QF](https://www.msi.com/Laptop/GE72-6QF-Apache-Pro.html#hero-overview)
> Intel I7 6700HQ
> Nvidia GTX 970

4.10.10-1-ARCH

~~i3wm tested, not tested running wayland or other server or DE, will test later.~~

* Issue DOES OCCUR in i3 wm (which runs on X)
* Issue DOES NOT OCCUR in gnome on Wayland. 
Will test other environments and DEs later.

AND, things only get weirder. Upon exiting Gnome and returning to i3 the program will launch without taking down my laptop screen; HOWEVER, the program enters seizure mode and flashes a white screen whenever the mouse is moved.

I'm considering that this could be an issue with your program and **hybrid graphics** so I tried running with DRI_PRIME=0 and 1 both. The same issue occured in both cases.

Note, I have never seen this issue with any other program, and I tested it at least 10 times to be sure it was with PM and not jack, cadence, or any other background process. Results are very reproducable, but also very, very strange.

**Comment by ventosus** [comment]
Thanks for the report, this is very much appreciated.

> Interface is visable but incorrectly scaled
> Interface rescales to match window size
This is expected behaviour, but needs fixing, yes.

> click on any object on screen -> laptop display goes black
This is not good indeed.

> program appears to respond sluggishly and even when holding CTRL to move an object the object may lose focus and be 'dropped'
> some visual artifacts result from sluggishness; lines and dots not rendered in real time and lag behind
This is a known issue and has already been fixed in https://github.com/OpenMusicKontrollers/patchmatrix/commit/a7170d0727d77848a330546b579d36e442b5594c

> [...] the program enters seizure mode and flashes a white screen whenever the mouse is moved.
Could be a problem with OpenGL buffer swapping on your specific hardware. Can you build from latest master to check for any improvements, where I've disabled some buffer swapping efficiency routines?

There are also nighlty binaries if you don't want to compile yourself.
https://dl.open-music-kontrollers.ch/patchmatrix/unstable/patchmatrix-latest-unstable.zip

**Comment by VegaDeftwing** [comment]
The linked binaries (what can I say, I'm lazy) seem to have fixed every issue I mentioned. Very responsive and no killing of the laptop's built in display. All is well.

**Comment by ventosus** [comment]
@VegaDeftwing awesome.

Time for a bugfix release then, I guess...
