### ISSUE TITLE
Save option

### ISSUE THREAD

**Issue by profejuanca** [OpenMusicKontrollers/patchmatrix#31]
Hi, it's a very nice program but two things is necessary for use like a connections manager.

1. A save option, it's tedious to open carla for connections saved and edit some new ones in Patchmatrix.
2. Lv2 and vst capabilities, well, it's much more dificult to implement, but maybe if charge a plugin manager this option is solved partially.

Great job!

**Comment by ventosus** [comment]
migrated to own forge <https://todo.open-music-kontrollers.ch/~hp/issues/3>
