### ISSUE TITLE
cmake problem

### ISSUE THREAD

**Issue by asbaklm** [OpenMusicKontrollers/patchmatrix#4]
Hi there, on Mint 18 I get this error when running cmake

"CMake Error at CMakeLists.txt:16 (if):
  if given arguments:

    "STREQUAL" "Release"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
"

**Comment by ventosus** [comment]
thanks for giving patchmatrix a spin

try
    cmake -DCMAKE_BUILD_TYPE="Release" ..

**Comment by ventosus** [comment]
fixed in: https://github.com/OpenMusicKontrollers/patchmatrix/commit/230ad44635130afcd0a25333d35e626c77bb419b
