### ISSUE TITLE
Compile error on Ubuntu 16.04 - "undefined reference to symbol 'sem_post@@GLIBC_2.2.5"

### ISSUE THREAD

**Issue by ViktorNova** [OpenMusicKontrollers/patchmatrix#5]
Hello! This looks like an awesome project and I am excited to try it out. I am getting this error when compiling on Ubuntu 16.04:

```
/usr/bin/ld: CMakeFiles/patchmatrix_monitor.dir/patchmatrix_monitor.c.o: undefined reference to symbol 'sem_post@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```

I have the jack and lv2 dev packages installed, am I missing something else?

**Comment by ventosus** [comment]
Thanks to giving patchmatrix a spin.

Seems like a missing linking step to pthreads. Can you check and report here if the latest commit fixes the issue for you?

https://github.com/OpenMusicKontrollers/patchmatrix/commit/d52c7b7b6ae66e079be5cbbf7ee3718a0adb573d

**Comment by ViktorNova** [comment]
This fixed it, thank you. 
Cool project!
