### ISSUE TITLE
Unknown sequence number while processing queue

### ISSUE THREAD

**Issue by wargreen** [OpenMusicKontrollers/patchmatrix#6]
Hi,
After build and try you software, when i add a widget the GUI close with this mesage :

```
❰wargreen❙~/Téléchargements/Audio/patchmatrix/build(git≠master)❱✘≻
./patchmatrix 0.12.0
Copyright (c) 2016-2017 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
patchmatrix: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
fish: './patchmatrix' terminated by signal SIGABRT (Abandon)
 [xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
patchmatrix: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

```
I hope i can try alls the functions one day, that seem very cool !

**Comment by ventosus** [comment]
Thanks for giving patchmatrix a spin.

Can you check if commit 72af0cff06dfa3be60afe8fb0ea67f76310f17c1 fixes the issue?

If you don't want to compile yourself, there's a precompiled binary at
https://dl.open-music-kontrollers.ch/patchmatrix/unstable/patchmatrix-latest-unstable.zip

**Comment by ventosus** [comment]
I've just seen that you started patchmatrix from within the build directory without first installing it.

That won't work, as mixer and monitor widget are separate applications which will only be found when patchmatrix was properly installed

    sudo make install

**Comment by ventosus** [comment]
529751198417a506aa72d366499838708e077423 fixes the crash, but won't add any monitor and mixer widgets, you need to properly install patchmatrix for those to work.

p.s. monitor and mixer widgets are seperate JACK applications (to take advantage for parallel execution in JACK2) and to also keep mixers 'alive' across patchmatrix invocations.
