### ISSUE TITLE
Some programs are not detected.

### ISSUE THREAD

**Issue by Rencer** [OpenMusicKontrollers/patchmatrix#8]
I'm using a 64-bit Manjaro Linux.
I installed Patchmatrix from the "community" repository. It runs, and I like the GUI and it has some cool features, but doen't works perfectly.

Before I installed this program, I used Patchage to connect together the different audio software and tools that I use. The reason that I installed PatchMatrix is because Patchage don't detect all the audio programs, tools, etc.
Sadly, it seems to be this software is even worse; it doesn't even detect some of the programs that Patchage is able to detect. One of the software is QMidiArp.
I don't tested this software further (what is working and what is not), because without QMidiArp I can't do anything.

I can't use many software that many people use (like Ladish) because they all required pulseaudio and/or doesn't work with ALSA. Or some of them even doesn'T work on a 64bit system.
I never want to install pulseaudio. It lags as hell, the sound quality is horrible. I tested it with Manjaro Linux and with Ubuntu, on 4 different computers (laptops and desktop PCs), with different build-in sound-hardware and with dedicated PCI  soundcards. It is always the same: with pulseaudio the sound quality is much worse compared to pure ALSA. And for some unknown reason it doesn't produce sound on the subwoofer. So I only use ALSA.

I really like to see a program that detects all the audio software and tools that can be installed from the repositories.
I really hope this software can be that one; it already looks nice and it already have some cool features that others don't.

**Comment by ventosus** [comment]
Thanks for reporting.

patchmatrix acoording to its README is a JACK patchbay in flow matrix style. So it does only show JACK clients and their AUDIO/CV/MIDI/OSC ports.

It does not show any ALSA AUDIO/MIDI ports and does not show any Pulseaudio AUDIO ports.

The only difference between patchage and patchmatrix is that patchage *does* show ALSA MIDI ports.

QMidiArp seems to be able to run directly on top of ALSA or JACK. Are you sure that you're running it with the JACK backend ?

**Comment by ventosus** [comment]
I've tested qmidiarp 0.6.5 here, and it shows up just fine in patchmatrix

    qmidiarp -j

**Comment by Rencer** [comment]
Thank you very much! That was the problem!

I used QMidiArp with the "-a" flag to use the ALSA Midi interface. My bad...
Using with the -j now it works.
